apiVersion: v1
kind: Pod
metadata:
    name: adhocns
    namespace: default
spec:
    hostUsers: false
    containers:
    - image: ubuntu
      name: ubuntu
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 10; done;" ]
---
apiVersion: v1
kind: Pod
metadata:
    name: hostns
    namespace: default
spec:
    hostUsers: true
    containers:
    - image: nginx
      name: nginx
---
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "sandbox"
  labels:
    name: "sandbox"
spec:
  hostUsers: false
  containers:
    -
      name: "sandbox"
      image: gcr.io/google_containers/busybox
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do date; echo `date`; sleep 5; done"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 4000
    runAsGroup: 4000
