apiVersion: v1
kind: Pod
metadata:
    name: adhocns
    namespace: default
spec:
    hostUsers: false
    containers:
    - image: ubuntu
      name: ubuntu
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 10; done;" ]
---
apiVersion: v1
kind: Pod
metadata:
    name: hostns
    namespace: default
spec:
    hostUsers: true
    containers:
    - image: nginx
      name: nginx
